springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs


spring:
  artemis:
    mode: native
    host: localhost
    port: 61616
    user: admin
    password: admin

message: 
  destination: /queue/notification